# Generated by Django 3.2.6 on 2021-08-25 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_alter_contract_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='Client',
            new_name='client',
        ),
    ]
