# Generated by Django 3.2.6 on 2021-09-06 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_contract_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='client',
        ),
    ]
