# Generated by Django 3.2.6 on 2021-09-06 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_remove_event_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventStatus',
            new_name='contract',
        ),
    ]
