# Generated by Django 3.2.6 on 2021-09-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_rename_eventstatus_event_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='attendees',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='eventDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(max_length=2048, null=True),
        ),
    ]
